### ISSUE TITLE
java.lang.NumberFormatException: For input string: "NAN"

### ISSUE THREAD

**Issue by yugecin** [thepilotslife/plchat#4]
```
java.lang.NumberFormatException: For input string: "NAN"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at plchat.PlayerData.share(PlayerData.java:158)
	at plchat.PlayerData.parse(PlayerData.java:74)
	at plchat.PlayerData.forName(PlayerData.java:21)
	at plchat.Main.getPlayerData(Main.java:383)
	at plchat.Main.playerCommand(Main.java:370)
	at plchat.Main.handleCommand(Main.java:206)
	at plchat.Main.chatconsumer(Main.java:69)
	at plchat.ChatThread.grab(ChatThread.java:174)
	at plchat.ChatThread.run(ChatThread.java:32)
```

**Comment by yugecin** [comment]
aba2536048d41e3abb54bb7e4fbaa89a84bc8bcb
